[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/webhook"
  status = 200

[[redirects]]
  from = "/signal"
  to = "/.netlify/functions/webhook"
  status = 200
